server:
  port: 8090
  error:
    include-message: always
  servlet:
    context-path: /api/v1
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

spring:
  application:
    name: moodscapes-backend
  datasource:
    url: jdbc:postgresql://localhost:5434/moodscapes
    username: moodscapes
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true

cors:
  allowed-origins: "*"
  allowed-headers: "*"
  allowed-methods: "*"
  exposed-headers: "*"

app:
  jwt:
    my-key: 432646294A404D635166546A576E5A7234753778214125442A472D4B6150645267556B58703273357638792F423F4528482B4D6251655468566D597133743677
    expiration-in-ms: 864000000

logging:
  level:
#    org.hibernate: DEBUG
#    org.springframework: DEBUG
    org:
      springframework:
        security: TRACE
