#DATABASE
POSTGRESQL_USERNAME: moodscapes_user
POSTGRESQL_PASSWORD: INU8HXsP5792aDEz8cSTCv0ItzA9kUxW
POSTGRESQL_HOST: dpg-cqp8rvdds78s73e6djo0-a
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: moodscapes
POSTGRESQL_PSQL_COMMAND: PGPASSWORD=INU8HXsP5792aDEz8cSTCv0ItzA9kUxW psql -h dpg-cqp8rvdds78s73e6djo0-a.oregon-postgres.render.com -U moodscapes_user moodscapes
POSTGRESQL_INTERNAL_URL: postgresql://moodscapes_user:INU8HXsP5792aDEz8cSTCv0ItzA9kUxW@dpg-cqp8rvdds78s73e6djo0-a/moodscapes
POSTGRESQL_EXTERNAL_URL: postgresql://moodscapes_user:INU8HXsP5792aDEz8cSTCv0ItzA9kUxW@dpg-cqp8rvdds78s73e6djo0-a.oregon-postgres.render.com/moodscapes

#SERVER
CONTAINER_PORT: 8090
ACTIVE_PROFILE: prod

#EMAIL CONFIG
EMAIL_HOST: romtecinvestment.com
EMAIL_PORT: 465
EMAIL_USERNAME: text@romtecinvestment.com
EMAIL_PASSWORD: Cz#v2I4x6Q#R
VERIFY_EMAIL_HOST:

#JWT
API_KEY: 432646294A404D635166546A576E5A7234753778214125442A472D4B6150645267556B58703273357638792F423F4528482B4D6251655468566D597133743677
EXPIRATION_IN_MS: 864000000

#OAUTH
GOOGLE_OAUTH_CLIENT_ID: 1088415841634-6l9chh4ub26tockvd95akgm8f1vf11jb.apps.googleusercontent.com
GOOGLE_OAUTH_CLIENT_SECRET: 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
