server:
  port: ${CONTAINER_PORT:8090}
  error:
    include-message: always
    path: /user/error
    whitelabel:
      enabled: false
  servlet:
    context-path: /api/v1
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

spring:
  application:
    name: moodscapes-backend
  profiles:
    active: ${ACTIVE_PROFILE:prod}
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false
    generate-ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        transport:
          protocol: smtp
        debug: true
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    verify:
      host: ${VERIFY_EMAIL_HOST}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            redirectUri: "{baseUrl}/login/oauth2/code/{googleId}"
            scope:
              - email
              - profile
        provider:
          google:
            authorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenUri: https://oauth2.googleapis.com/token
            userInfoUri: https://openidconnect.googleapis.com/v1/userinfo
            userNameAttribute: sub

cors:
  allowed-origins: "*"
  allowed-headers: "*"
  allowed-methods: "*"
  exposed-headers: "*"

app:
  auth:
    magiclink:
      base-url: http://localhost:8090
  jwt:
    secret-key: ${API_KEY}
    expiration-in-ms: ${EXPIRATION_IN_MS}

logging:
  level:
#    org.hibernate: DEBUG
#    org.springframework: DEBUG
    org:
      springframework:
        security: TRACE
