#DATABASE
POSTGRESQL_USERNAME: moodscapes
POSTGRESQL_PASSWORD: admin
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5434
POSTGRESQL_DATABASE: moodscapes

#SERVER
CONTAINER_PORT: 8090
ACTIVE_PROFILE: prod

#EMAIL CONFIG
EMAIL_HOST: romtecinvestment.com
EMAIL_PORT: 465
EMAIL_USERNAME: text@romtecinvestment.com
EMAIL_PASSWORD: Cz#v2I4x6Q#R
VERIFY_EMAIL_HOST:

#JWT
API_KEY: 432646294A404D635166546A576E5A7234753778214125442A472D4B6150645267556B58703273357638792F423F4528482B4D6251655468566D597133743677
EXPIRATION_IN_MS: 864000000

#OAUTH
GOOGLE_OAUTH_CLIENT_ID: 827351830165-3e4mnj7o009t5ont1mv7lug5jdst466f.apps.googleusercontent.com
GOOGLE_OAUTH_CLIENT_SECRET: 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
